### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [KniginAleksey/Study-in-the-BSA#1]
@KniginAleksey, привіт, а можна додати до репозиторію ще **README.md** з описом проекту?
*P. S. Самокат зайшов норм.*

**Comment by KniginAleksey** [comment]
Конечно, я работаю над этим =)

**Comment by volodymyr-kushnir** [comment]
@KniginAleksey отлично! И еще несколько [**лайфхаков и подсказок**](https://github.com/volodymyr-kushnir/agenda).

**Comment by KniginAleksey** [comment]
Спасибо. Буду изучать ;-)
